### ISSUE TITLE
Lost Comics

### ISSUE THREAD

**Issue by diotodd** [Creckeryop/NOBORU#115]
I can't find some of the comics from ReadComicsOnline even though they exist in the site.
![Ekran Alıntısı](https://user-images.githubusercontent.com/69166498/166265543-930907e1-0063-4300-a86b-2360a53ca441.PNG)
![2022-05-02-194656](https://user-images.githubusercontent.com/69166498/166265560-cdff2498-4ebe-4f4c-b02b-9ba35674be98.png)

**Comment by Creckeryop** [comment]
Noboru has two ReadComic*Online catalogs (1st is ReadComicOnline 2nd is ReadComicsOnline). Maybe you were searching on https://readcomicsonline.ru/ catalog instead of https://readcomiconline.li/ catalog (ReadComicOnline.to doesn't work because they've enabled anti-ddos guard, so Noboru can't pass throw that thing, sorry for that :( )

**Comment by diotodd** [comment]
Oh, okay
