### ISSUE TITLE
[Feature request] Add filters in parsers

### ISSUE THREAD

**Issue by eze92** [Creckeryop/NOBORU#42]
I have noticed that for example in mangadex the language filter does not work, is it possible to apply it so that you do not have to randomly search for those that are in the language you want to read?

**Comment by Creckeryop** [comment]
You should know that mangadex dont have that filter (only in search, but you should log in), and i did something that *looks like filter* but it shows only chapters that your language. So that's not possible (without more internet usage) to get available languages for manga from popular, latest page

**Comment by Creckeryop** [comment]
Oh i am sorry, i was mistaken, it's possible to get manga with language you want

**Comment by Creckeryop** [comment]
Next time write in parsers-repo (because it's parser issue not app) [Parsers-repo](https://github.com/Creckeryop/NOBORU-parsers)

**Comment by Creckeryop** [comment]
This filter doesnt work on 
https://mangadex.org/titles
https://mangadex.org/titles?s=7#listing
(i use these pages to take manga)

**Comment by Creckeryop** [comment]
Added filters in 41e165cd875eb3c681630b7b21b7336b48451648
