### ISSUE TITLE
[Feature Request] empty catalogues

### ISSUE THREAD

**Issue by Nazimhdm** [Creckeryop/NOBORU#99]
Hi! Most of the catalogues are empty or the websites are closed, is it possible to update them, or add new catalogues from other websites, anyway, thanks for the app, it's a gem
Also, I would like to ask if it's possible to put french catalogues again, like japscan and scanfr

**Comment by Creckeryop** [comment]
I can't update catalogues for closed sites
Also some of sites updated their code, so most of catalogues doesn't work because sites now has antibot check (including captcha, i really can't do anything with this), some of sites still doesn't have antibot check, but, i really can't check every catalog  every day, so you can write me which catalog doesn't work(or if catalog works, but some of manga doesn't work, write me detailed information about error: manga, chapter, catalog...)
I want to add a lot of catalogues for every language, but i need links, I don't know how to find checked, trusted sites.

Sorry, some of catalogues can't be updated.
But, you can advice me site. Maybe i will add it (depending on security level or site code)
Sorry, if i were too rude. Also for bad English

**Comment by Nazimhdm** [comment]
Hi! sorry for the late reply, well I now understand what went wrong with the catalogues, so I guess we can't do anything about them, but that's alright, here are some of the catalogues in english that don't work for me or have issues: 
- mangadex(closed).
- mangahub(some mangas don't open and show this: unknown error (Parser's) ).
- mangapanda(closed).
- mangareader(closed).
- mangaseeonline(closed).
- vlcomic(closed).
I think these are all the catalogues that don't work in english

Now for the french websites that I can suggest:
japscan is the best in my opinion in french.

Anyway, you've done a great job with noboru, and I can't thank you enough for it, I know that you're doing the best and you have all my support, if I find anything that could help improve the app, i'll notify you.

Have a good day/night wherever you are

**Comment by Creckeryop** [comment]
i heard a lot about japscan, I think it's really nice site, but i can't add it, site is protected from getting any image, and i really can't do anything with that, sorry!

Also thanks for your reply!
